---
title: "LatinR Conference Materials"
---


Materials for [LatinR](https://latinr.org/) 

Stephanie Zimmer is a Senior Research Statistician at RTI with a decade of experience in survey sampling and design, survey weighting and analysis, and data management. Stephanie is an expert statistical programmer and instructor. Dr. Zimmer co‑authored the book Exploring Complex Survey Data Analysis Using R.

# [Transforming a team to open-source first](slides.qmd)

Three years ago, a small group at my work formed an open-source software committee in a land where statisticians primarily used a commercially available software. We wanted to champion an open-source first initiative and convert people and projects to using open-source software. I will talk about what we did to make this happen and how the process accelerated. Some of the key things I was involved in were open-source office hours which formed a great community, developing an R package when we couldn’t find something we needed in R, and developing small examples of common things we do in our work in R with a comparison to the prior method.